### ISSUE TITLE
Comment functionality?

### ISSUE THREAD

**Issue by esigler** [jimmycuadra/lita#109] opened 2015-05-27 17:02 UTC
Howdy!  So, an increasingly common behavior we have for our internal plugins is to have a "comment" at the end of the chat command, like so:

```
user> !unlock production # Hey everyone, all done
bot> production unlocked
```

and occasionally we can use the comment in the handler as well:

```
user> !deploy something to production # Hey, rolling out that new feature
bot> Deploying something/master to production
...
bot> something/master was deployed to production with the note: "Hey, rolling out that new feature"
```

I'm wondering if it would be worth extracting this logic as either an extension or robot-wide behavior.  It could have the following properties:

1. Something similar to alias where a bot can have a comment token, such as #, that obscures everything after that token from being matched by the route
2. Pass the extracted comment to the handler as a separate field

Worth doing?

**Comment by jimmycuadra** [comment] 2015-05-27 19:11
Cool idea! It'd make sense as an extension, I think. Leave a comment if you have any trouble implementing it with the current extension points.

**Comment by braiden-vasco** [comment] 2015-06-23 14:07
I'm trying to implement this now. I can't implement this as an extension because of the following reasons:
* Extensions has no configuration, but I want to allow user to configure which characters to use for comments' delimiters.
* Extensions are made to require them in other plugins, not in Lita's project Gemfile.

I also can't implement this as a handler, cause the original route will be triggered in any case.

**Comment by jimmycuadra** [comment] 2015-06-24 01:34
Those points are both intentional. Extensions are a mechanism to extend Lita's core functionality for plugin development. The end user should not be aware of them. Plugins that want to use comment functionality would require and load your extension, which provides configuration via its own API. See lita-confirmation for an example.

**Comment by braiden-vasco** [comment] 2015-06-24 01:49
The user should make a decision of use comments. I want to be able to add comments to any command, regardless of whether it is provided by the creator of the handler or not. Also I want to let user define the syntax of comments.

**Comment by jimmycuadra** [comment] 2015-06-24 03:21
Although I like the comment idea, I don't like the idea of Lita itself needing to know anything about it, or the idea of it being globally applied to plugins that have not opted into its use, since it involves the actual content of messages. Handler A might have existing semantics for the character that Handler B uses as its comment delimiter, which could easily cause bugs or unexpected behavior.

**Comment by jimmycuadra** [comment] 2015-08-21 06:37
Closing because I think an extension is the appropriate way to implement this.

**Closed by jimmycuadra** 2015-08-21 06:37 UTC
Labels: component/extensions, effort/normal, status/under consideration, type/feature
