### ISSUE TITLE
Kvetch if someone tries to run a command they aren't authorized to run.

### ISSUE THREAD

**Issue by MrJoy** [jimmycuadra/lita#97] opened 2015-04-28 21:10 UTC
I have spent a bunch of time reviewing my regexes to see if I mucked something up when in reality I forgot to add myself to the relevant group.  Having an explicit error message would be handy.

**Comment by harlanbarnes** [comment] 2015-04-28 21:17
I'd guess that this is a duplicate to (or at least in the same vein as) the one that I opened at #59. I had mentioned to Jimmy that was low priority because I had a good workaround.

This is what I did in `lita-rundeck`:

```ruby
def user_in_group?(user)
  Lita::Authorization.user_in_group?(user,:whatever_your_group_is_called)
end

unless user_in_group?(response.user)
  response.reply t("run.unauthorized")
  return
end
```

**Comment by jimmycuadra** [comment] 2015-04-29 00:09
Confirmed dupe of #59.

**Closed by jimmycuadra** 2015-04-29 00:09 UTC
Labels: duplicate
